Basic tf structure
sysco-middleware/AzureChallengeTeam2 pull request #2
Opened 2023-04-03 21:23 UTC by GuruduGanesh

Please review the initial structure.

2023-04-04 10:58 UTC, dhayanands commented
What is the going to be difference between security, network & route?

should the network & route be part of the same module?

2023-04-11 10:07 UTC, meejurusiva requested changes
Are we going to use existing codes in  azure modules or are those for references ?

2023-04-11 10:07 UTC, meejurusiva commented on modules/azurerm_route_table/outputs.tf
Is this need to be removed ? Can you check.

2023-04-12 10:39 UTC, GuruduGanesh commented on modules/azurerm_route_table/outputs.tf
Yes, It Microsoft provided module. We need to use it in our code.
Source of modules is - https://github.com/sysco-middleware/terraform-azure-modules

2023-04-12 10:40 UTC, dhayanands approved these changes
for now we can start with this code

2023-04-12 10:40 UTC, meejurusiva approved these changes

2023-04-12 10:42 UTC, merged